let cards = [ 
	{ id: 1, deck: false, name: "Céu limpo", weather: true, ability_id: 9, image: "image/card/weather/clear.png" },
	{ id: 2, deck: false, name: "Céu limpo", weather: true, ability_id: 9, image: "image/card/weather/clear.png" },
	{ id: 3, deck: false, name: "Céu limpo", weather: true, ability_id: 9, image: "image/card/weather/clear.png" },
	{ id: 4, deck: false, name: "Nevasca Impiedosa", weather: true, ability_id: 10, image: "image/card/weather/frost.png" },
	{ id: 5, deck: false, name: "Nevasca Impiedosa", weather: true, ability_id: 10, image: "image/card/weather/frost.png" },
	{ id: 6, deck: false, name: "Nevasca Impiedosa", weather: true, ability_id: 10, image: "image/card/weather/frost.png" },
	{ id: 7, deck: false, name: "Neblina Severa", weather: true, ability_id: 11, image: "image/card/weather/fog.png" },
	{ id: 8, deck: false, name: "Neblina Severa", weather: true, ability_id: 11, image: "image/card/weather/fog.png" },
	{ id: 9, deck: false, name: "Neblina Severa", weather: true, ability_id: 11, image: "image/card/weather/fog.png" },
	{ id: 10, deck: false, name: "Temporal", weather: true, ability_id: 12, image: "image/card/weather/rain.png" },
	{ id: 11, deck: false, name: "Temporal", weather: true, ability_id: 12, image: "image/card/weather/rain.png" },
	{ id: 12, deck: false, name: "Temporal", weather: true, ability_id: 12, image: "image/card/weather/rain.png" },
	{ id: 13, deck: false, name: "Fogaréu", power: false, ability_id: 6, image: "image/card/special/burn.png" },
	{ id: 14, deck: false, name: "Fogaréu", power: false, ability_id: 6, image: "image/card/special/burn.png" },
	{ id: 15, deck: false, name: "Fogaréu", power: false, ability_id: 6, image: "image/card/special/burn.png" },
	{ id: 16, deck: false, name: "Grande General", power: false, ability_id: 1, image: "image/card/special/general.png" },
	{ id: 17, deck: false, name: "Grande General", power: false, ability_id: 1, image: "image/card/special/general.png" },
	{ id: 18, deck: false, name: "Grande General", power: false, ability_id: 1, image: "image/card/special/general.png" },
	{ id: 19, deck: 1, hero: true, range: 'close', name: "Marco Vipsânio Agripa", power: 15, image: "image/card/rome/agripa.png" },
	{ id: 20, deck: 1, hero: true, range: 'close', name: "Cornélio Cipião Africano", power: 10, image: "image/card/rome/cipiao.png" },
	// { id: 19, deck: 1, hero: true, range: 'close', name: "Super Slime", power: 15, image: "image/card/personal/super-slime.png" },
	// { id: 20, deck: 1, hero: true, range: 'close', name: "Trovão", power: 10, image: "image/card/personal/trovao.png" },
	{ id: 21, deck: 1, hero: true, range: 'close', name: "Lúcio Emílio Paulo Macedônico", power: 7, image: "image/card/rome/aemilius.png" },
	{ id: 22, deck: 1, hero: false, range: 'close', name: "Legado", power: 2, ability_id: 1, image: "image/card/rome/legacy.png" },
	{ id: 23, deck: 1, hero: false, range: 'close', name: "Legado", power: 2, ability_id: 1, image: "image/card/rome/legacy2.png" },
	{ id: 24, deck: 1, hero: false, range: 'close', name: "Centurião", power: 5, ability_id: 8, image: "image/card/rome/centurion.png" },
	{ id: 25, deck: 1, hero: false, range: 'close', name: "Centurião", power: 5, ability_id: 8, image: "image/card/rome/centurion2.png" },
	{ id: 26, deck: 1, hero: false, range: 'close', name: "Centurião", power: 5, ability_id: 8, image: "image/card/rome/centurion3.png" },
	{ id: 27, deck: 1, hero: false, range: 'close', name: "Centurião", power: 5, ability_id: 8, image: "image/card/rome/centurion4.png" },
	{ id: 28, deck: 1, hero: false, range: 'close', name: "Centúria Romana", power: 8, ability_id: 5, image: "image/card/rome/century.png" },
	{ id: 29, deck: 1, hero: false, range: 'close', name: "Centúria Romana", power: 8, ability_id: 5, image: "image/card/rome/century2.png" },
	{ id: 30, deck: 1, hero: false, range: 'close', name: "Centúria Romana", power: 8, ability_id: 5, image: "image/card/rome/century3.png" },
	{ id: 31, deck: 1, hero: false, range: 'close', name: "Legionario", power: 7, image: "image/card/rome/legionary.png" },
	{ id: 32, deck: 1, hero: false, range: 'close', name: "Legionario", power: 5, image: "image/card/rome/legionary2.png" },
	{ id: 33, deck: 1, hero: false, range: 'close', name: "Legionario", power: 5, image: "image/card/rome/legionary3.png" },
	{ id: 34, deck: 1, hero: false, range: 'ranged', name: "Lançador de Plumbata", power: 6, image: "image/card/rome/plumbata.png" },
	{ id: 35, deck: 1, hero: false, range: 'ranged', name: "Lançador de Plumbata", power: 3, image: "image/card/rome/plumbata2.png" },
	{ id: 36, deck: 1, hero: false, range: 'ranged', name: "Lançador de Plumbata", power: 4, image: "image/card/rome/plumbata3.png" },
	{ id: 37, deck: 1, hero: false, range: 'siege', name: "Paulo de Tarso", power: 1, ability_id: 3, image: "image/card/rome/tarso.png" },
	{ id: 38, deck: 1, hero: false, range: 'siege', name: "Paulo de Tarso", power: 1, ability_id: 3, image: "image/card/rome/tarso.png" },
	{ id: 39, deck: 1, hero: false, range: 'close', name: "Paulo de Tarso", power: 1, ability_id: 3, image: "image/card/rome/tarso.png" }
];

module.exports = cards;